apiVersion: v1                    
kind: Namespace
metadata:
  name: pacman-ns                             
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: pacman
  namespace: pacman-ns
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - pacman
---
apiVersion: v1                      
kind: Namespace
metadata:
  name: ggithubcom-ocp-power-demos-open-cluster-management-ns
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: ggithubcom-ocp-power-demos-open-cluster-management
  namespace: ggithubcom-ocp-power-demos-open-cluster-management-ns
spec:
  type: Git
  pathname: 'https://github.com/ocp-power-demos/open-cluster-management'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: application-samples/pacman
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: pacman
  name: pacman-subscription-1
  namespace: pacman-ns
spec:
  channel: ggithubcom-ocp-power-demos-open-cluster-management-ns/ggithubcom-ocp-power-demos-open-cluster-management
  placement:
    placementRef:
      kind: PlacementRule
      name: pacman-placement-1
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: pacman
  name: pacman-placement-1
  namespace: pacman-ns
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"

